// const SUCCESS_STATUS = 0;
// const INCLUDE_FAILURE_STATUS = 1;
// const PRELUDE_FAILURE_STATUS = 2;
// const CONTENT_FAILURE_STATUS = 3;
// const MISSING_NEGATIVE_STATUS = 4;
// const PENDING_PROMISE_STATUS = 5;
// const ASYNC_PRINT_STATUS = 6;
// const ASYNC_MISSING_STATUS = 7;

// exports.SUCCESS_STATUS = SUCCESS_STATUS;
// exports.INCLUDE_FAILURE_STATUS = INCLUDE_FAILURE_STATUS;
// exports.PRELUDE_FAILURE_STATUS = PRELUDE_FAILURE_STATUS;
// exports.CONTENT_FAILURE_STATUS = CONTENT_FAILURE_STATUS;
// exports.MISSING_NEGATIVE_STATUS = MISSING_NEGATIVE_STATUS;
// exports.PENDING_PROMISE_STATUS = PENDING_PROMISE_STATUS;
// exports.ASYNC_PRINT_STATUS = ASYNC_PRINT_STATUS;
// exports.ASYNC_MISSING_STATUS = ASYNC_MISSING_STATUS;

// const SUCCESS = 0;
// const INCLUDE_FAILURE = 1;
// const PRELUDE_FAILURE = 2;
// const CONTENT_FAILURE = 3;
// const MISSING_NEGATIVE = 4;
// const PENDING_PROMISE = 5;
// const ASYNC_PRINT = 6;
// const ASYNC_MISSING = 7;

exports.SETUP_FAILURE = "SETUP_FAILURE";
exports.INCLUDE_FAILURE = "include-failure";
exports.PRELUDE_FAILURE = "prelude-failure";
exports.CONTENT_FAILURE = "content-failure";
exports.MISSING_NEGATIVE = "missing-negative";
exports.PENDING_PROMISE = "pending-promise";
exports.ASYNC_PRINT = "async-print";
exports.ASYNC_MISSING = "async-missing";
